### ISSUE TITLE
Can't run individual namespace tests with :only

### ISSUE THREAD

**Issue by jamesmarkcook** [FundingCircle/factory-time#10]
When running a command such as `lein test :only app_name.namespace` in a test that uses the `build :factory-name` function the following error occurs:

`java.lang.IllegalArgumentException: No method in multimethod 'get-factory' for dispatch value: :factory-name`

This error does not occur when simply running `lein test`.

For clarification, this is when using factory-time in our application tests, not testing factory-time itself.

**Comment by jamesmarkcook** [comment]
The problem was we weren't requiring the file where our factories were being defined.

**Comment by jspc** [comment]
Amateur hour.
